export default interface Image {
    date: string,
    imageid: number,
    copyright: string,
    idsid: number,
    description: string,
    technique: string,
    renditionnumber: string,
    displayorder: number,
    baseimageurl: string,
    alttext: string,
    width: number,
    publiccaption: string,
    iiifbaseuri: string,
    height: number,
}
